import "../../public/styles/index.scss";
import "swiper/css";

import AnimatePresenceWrapper from "./_components/common/wrapper/animate-wrapper";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import PageTransition from "./_components/common/page-transition/page-transition";
import ReduxProvider from "./_components/common/wrapper/redux-provider";

const mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PV Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <ReduxProvider>
          <AnimatePresenceWrapper>
            <PageTransition>{children}</PageTransition>
          </AnimatePresenceWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
