import "../../public/styles/index.scss";

import AnimatePresenceWrapper from "./_components/common/animate-presence/animate-presence";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import PageTransition from "./_components/common/page-transition/page-transition";

const mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PV Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <AnimatePresenceWrapper>
          <PageTransition>{children}</PageTransition>
        </AnimatePresenceWrapper>
      </body>
    </html>
  );
}
